version: '2'
services:
  rabbitmq:
    image: rabbitmq
    hostname: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    expose:
      - 5672
      - 15672
    depends_on:
      - db
    restart: always

  db:
    image: mariadb
    hostname: db
    environment:
      - MYSQL_ROOT_PASSWORD=qwe123
      - MYSQL_DATABASE=rematch
      - MYSQL_USER=rematch
      - MYSQL_PASSWORD=rematchpassword
    expose:
     - 3306
    restart: always

  web:
    hostname: web
    build:
      context: ..
      dockerfile: server/Dockerfile
    volumes:
      - /home/deb/rematch/
    ports:
      - "8000:8000"
    expose:
      - "8000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=rematch
      - MYSQL_USER=rematch
      - MYSQL_PASSWORD=rematchpassword
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASSWORD=mypass
      - DJANGO_SETTINGS_MODULE=rematch.settings.docker
    links:
      - "db:db"
      - "rabbitmq:rabbitmq"
    depends_on:
      - db
      - rabbitmq
    restart: always
